name: automate-push-tasks
on: push
jobs:
  make-README:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "././requirements.txt"
      - name: Make README
        run: bash make_README.bash
      - name: Clean README
        run: python3 clean_README.py
      - name: Upload README
        uses: actions/upload-artifact@v2
        with:
          name: output-README
          path: README.md
      - name: Commit new README.md
        run: |
          git config --global user.name 'yrom1'
          git config --global user.email '${{ secrets.YROM1_EMAIL }}'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Make new README.md." || true
          git push || true
